version: 2

sources:
  - name: staging
    database: usgs-earthquake-data #project
    schema: usgs_earthquake_data #dataset

    tables:
      - name: usgs_earthquake_data_raw_2024

models:
  - name: staging_usgs_earthquake_data
    description: staged data from BigQuery Raw table 
