version: 0.1.1
default:

  # Google
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "{{ env_var('MAGE_GOOGLE_SERVICE_ACCOUNT') }}"
  GOOGLE_LOCATION: "{{ env_var('GCP_LOCATION') }}"

  # # PostgresSQL
  # POSTGRES_CONNECT_TIMEOUT: 10
  # POSTGRES_DBNAME: postgres
  # POSTGRES_SCHEMA: public # Optional
  # POSTGRES_USER: username
  # POSTGRES_PASSWORD: password
  # POSTGRES_HOST: hostname
  # POSTGRES_PORT: 5432

  # # DuckDB
  # DUCKDB_DATABASE: database
  # DUCKDB_SCHEMA: main