services:
  mage:
    image: mageai/mageai:latest
    container_name: mage
    command: mage start /home/src/mage/${MAGE_PROJECT_NAME}
    build:
      context: ./mage/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5