triggers:
- envs: []
  last_enabled_at: 2024-04-13 18:03:18.680524
  name: API_TRIGGER_CREATED_FROM_CODE
  pipeline_uuid: dbt_pipeline
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-04-12 17:00:39.038407
  status: active
  variables: null
