version: 2

sources:
  - name: staging
    database: usgs-earthquake-data #project
    schema: usgs_earthquake_data #dataset
    tables:
      - name: usgs_earthquake_data_raw_2024

models:
  - name: staging_usgs_earthquake_data
    description: staged data from BigQuery Raw table 
    columns:
      - name: unique_event_id
        data_type: string
        description: Unique identifier for each event

      - name: event_id
        data_type: string
        description: Event identifier

      - name: event_datetime
        data_type: timestamp
        description: Date and time of the event

      - name: last_updated
        data_type: timestamp
        description: Timestamp for when the event data was last updated

      - name: event_date
        data_type: date
        description: Date of the event

      - name: event_time
        data_type: time
        description: Time of the event

      - name: date_partition
        data_type: date
        description: Date partition for data organization

      - name: mag_cluster_partition
        data_type: string
        description: Partition for magnitude clustering

      - name: event_latitude
        data_type: float64
        description: Latitude of the event location

      - name: event_longitude
        data_type: float64
        description: Longitude of the event location

      - name: descriptive_geographic_region
        data_type: string
        description: Description of the geographic region

      - name: event_type
        data_type: string
        description: Type of the event

      - name: event_magnitude
        data_type: numeric
        description: Magnitude of the event

      - name: depth_km
        data_type: numeric
        description: Depth of the event in kilometers

      - name: magnitude_conversion_type
        data_type: string
        description: Type of magnitude conversion

      - name: no_stations_to_calculate_location
        data_type: numeric
        description: Number of stations used to calculate event location

      - name: largest_gap_between_stations
        data_type: numeric
        description: Largest gap between stations for event location calculation

      - name: dist_epicenter_to_station_degrees
        data_type: numeric
        description: Distance from epicenter to station in degrees

      - name: root_mean_square_residual_seconds
        data_type: numeric
        description: Root mean square residual in seconds

      - name: horizontal_location_error_km
        data_type: numeric
        description: Horizontal location error in kilometers

      - name: depth_uncertainty_km
        data_type: numeric
        description: Depth uncertainty in kilometers

      - name: magnitude_uncertainty
        data_type: numeric
        description: Magnitude uncertainty

      - name: no_stations_to_calculate_magnitude
        data_type: numeric
        description: Number of stations used to calculate magnitude

      - name: event_review_status
        data_type: string
        description: Review status of the event

      - name: data_contributor_network_id
        data_type: string
        description: ID of the data contributor network

      - name: data_contributor_network_name
        data_type: string
        description: Name of the data contributor network

      - name: network_reported_by_id
        data_type: string
        description: ID of the network that reported the event

      - name: network_reported_by_name
        data_type: string
        description: Name of the network that reported the event

      - name: network_magnitude_author_id
        data_type: string
        description: ID of the network magnitude author

      - name: network_magnitude_author_name
        data_type: string
        description: Name of the network magnitude author
