name: 'usgs_earthquake_data'
version: '1.0.0'
config-version: 2

profile: 'usgs_earthquake_data'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  usgs_earthquake_data:
      staging:
          materialized: view
      core:
          materialized: table

seeds:
    usgs_earthquake_data:
      