triggers:
- envs: []
  last_enabled_at: 2024-04-10 09:45:31.790945
  name: initial_project_trigger
  pipeline_uuid: usgs_earthquake_data_ingest_historic
  schedule_interval: '@once'
  schedule_type: time
  settings:
    create_initial_pipeline_run: true
  sla: null
  start_time: 2024-04-16 09:00:00
  status: active
  variables: {}
